package usecase

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/HieuLapTrinh04/learning-management-system/internal/apperrors"
	"github.com/HieuLapTrinh04/learning-management-system/internal/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

func (m *MockReviewRepository) CreateReview(ctx context.Context, review *models.Review) error {
	args := m.Called(ctx, review)
	return args.Error(0)
}

func (m *MockReviewRepository) GetReviewByStudentAndCourse(ctx context.Context, studentID, courseID uint) (*models.Review, error) {
	args := m.Called(ctx, studentID, courseID)
	var r0 *models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) UpdateReview(ctx context.Context, review *models.Review) error {
	args := m.Called(ctx, review)
	return args.Error(0)
}

func (m *MockReviewRepository) GetReviewByID(ctx context.Context, reviewID uint) (*models.Review, error) {
	args := m.Called(ctx, reviewID)
	var r0 *models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) ListReviewsByCourseID(ctx context.Context, courseID uint, isAdminOrTeacher bool) ([]models.Review, error) {
	args := m.Called(ctx, courseID, isAdminOrTeacher)
	var r0 []models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).([]models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) GetCourseRatingStats(ctx context.Context, courseID uint) (map[int]int64, int64, float64, error) {
	args := m.Called(ctx, courseID)
	var r0 map[int]int64
	if args.Get(0) != nil {
		r0 = args.Get(0).(map[int]int64)
	}
	return r0, args.Get(1).(int64), args.Get(2).(float64), args.Error(3)
}

func (m *MockReviewRepository) ListAllReviews(ctx context.Context, page, limit int, search string) ([]models.Review, int64, error) {
	args := m.Called(ctx, page, limit, search)
	var r0 []models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).([]models.Review)
	}
	return r0, args.Get(1).(int64), args.Error(2)
}

// MockCourseRepository and MockEnrollmentRepository
type MockCourseRepository struct {
	mock.Mock
}

func (m *MockCourseRepository) Create(ctx context.Context, course *models.Course) error {
	return nil
}
func (m *MockCourseRepository) GetByID(ctx context.Context, id uint) (*models.Course, error) {
	args := m.Called(ctx, id)
	var r0 *models.Course
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Course)
	}
	return r0, args.Error(1)
}
func (m *MockCourseRepository) Update(ctx context.Context, course *models.Course) error {
	return nil
}
func (m *MockCourseRepository) Delete(ctx context.Context, id uint) error {
	return nil
}
func (m *MockCourseRepository) ListAll(ctx context.Context, page, limit int, status string) ([]models.Course, int64, error) {
	return nil, 0, nil
}
func (m *MockCourseRepository) ListByTeacherID(ctx context.Context, teacherID uint, page, limit int) ([]models.Course, int64, error) {
	return nil, 0, nil
}

type MockEnrollmentRepository struct {
	mock.Mock
}

func (m *MockEnrollmentRepository) Enroll(ctx context.Context, enrollment *models.Enrollment) error {
	return nil
}
func (m *MockEnrollmentRepository) GetByStudentAndCourse(ctx context.Context, studentID, courseID uint) (*models.Enrollment, error) {
	args := m.Called(ctx, studentID, courseID)
	var r0 *models.Enrollment
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Enrollment)
	}
	return r0, args.Error(1)
}
func (m *MockEnrollmentRepository) ListByStudentID(ctx context.Context, studentID uint) ([]models.Enrollment, error) {
	return nil, nil
}
func (m *MockEnrollmentRepository) UpdateProgress(ctx context.Context, enrollmentID uint, progress float64) error {
	return nil
}
func (m *MockEnrollmentRepository) GetEnrollmentStatsByTeacher(ctx context.Context, teacherID uint) (int64, float64, error) {
	return 0, 0, nil
}


func TestSubmitReview(t *testing.T) {
	mockReviewRepo := new(MockReviewRepository)
	mockCourseRepo := new(MockCourseRepository)
	mockEnrollmentRepo := new(MockEnrollmentRepository)
	useCase := NewReviewUseCase(mockReviewRepo, mockCourseRepo, mockEnrollmentRepo)

	ctx := context.Background()

	t.Run("Success", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(1), uint(1)).Return(&models.Enrollment{}, nil).Once()
		mockReviewRepo.On("GetReviewByStudentAndCourse", ctx, uint(1), uint(1)).Return(nil, errors.New("not found")).Once()
		mockReviewRepo.On("CreateReview", ctx, mock.AnythingOfType("*models.Review")).Return(nil).Once()

		err := useCase.SubmitReview(ctx, 1, 1, 5, "Great course")
		assert.NoError(t, err)

		mockEnrollmentRepo.AssertExpectations(t)
		mockReviewRepo.AssertExpectations(t)
	})

	t.Run("Not Enrolled", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(2), uint(1)).Return(nil, errors.New("not found")).Once()

		err := useCase.SubmitReview(ctx, 2, 1, 5, "Great course")
		assert.Error(t, err)
		assert.IsType(t, &apperrors.AppError{}, err)

		mockEnrollmentRepo.AssertExpectations(t)
	})

	t.Run("Invalid Rating", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(1), uint(1)).Return(&models.Enrollment{}, nil).Once()
		mockReviewRepo.On("GetReviewByStudentAndCourse", ctx, uint(1), uint(1)).Return(nil, errors.New("not found")).Once()

		err := useCase.SubmitReview(ctx, 1, 1, 6, "Great course")
		assert.Error(t, err)

		mockEnrollmentRepo.AssertExpectations(t)
		mockReviewRepo.AssertExpectations(t)
	})
}

func TestReplyToReview(t *testing.T) {
	mockReviewRepo := new(MockReviewRepository)
	mockCourseRepo := new(MockCourseRepository)
	mockEnrollmentRepo := new(MockEnrollmentRepository)
	useCase := NewReviewUseCase(mockReviewRepo, mockCourseRepo, mockEnrollmentRepo)

	ctx := context.Background()

	t.Run("Success", func(t *testing.T) {
		review := &models.Review{
			BaseModel: models.BaseModel{ID: 1},
			CourseID:  1,
			StudentID: 1,
			Rating:    5,
		}
		course := &models.Course{
			BaseModel: models.BaseModel{ID: 1},
			TeacherID: 1,
		}

		mockReviewRepo.On("GetReviewByID", ctx, uint(1)).Return(review, nil).Once()
		mockCourseRepo.On("GetByID", ctx, uint(1)).Return(course, nil).Once()
		mockReviewRepo.On("UpdateReview", ctx, mock.AnythingOfType("*models.Review")).Return(nil).Once()

		err := useCase.ReplyToReview(ctx, 1, 1, "Thank you")
		assert.NoError(t, err)

		mockReviewRepo.AssertExpectations(t)
		mockCourseRepo.AssertExpectations(t)
	})

	t.Run("Forbidden - Not the teacher", func(t *testing.T) {
		review := &models.Review{
			BaseModel: models.BaseModel{ID: 1},
			CourseID:  1,
		}
		course := &models.Course{
			BaseModel: models.BaseModel{ID: 1},
			TeacherID: 2, // Different teacher
		}

		mockReviewRepo.On("GetReviewByID", ctx, uint(1)).Return(review, nil).Once()
		mockCourseRepo.On("GetByID", ctx, uint(1)).Return(course, nil).Once()

		err := useCase.ReplyToReview(ctx, 1, 1, "Thank you")
		assert.Error(t, err)
		assert.IsType(t, &apperrors.AppError{}, err)

		mockReviewRepo.AssertExpectations(t)
		mockCourseRepo.AssertExpectations(t)
	})
}
