package usecase

import (
	"context"
	"errors"
	"testing"

	"github.com/HieuLapTrinh04/learning-management-system/internal/apperrors"
	"github.com/HieuLapTrinh04/learning-management-system/internal/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

func (m *MockReviewRepository) ReplyReview(ctx context.Context, id uint, reply string) error {
	return nil
}
func (m *MockReviewRepository) DeleteReview(ctx context.Context, id uint) error {
	return nil
}

func (m *MockReviewRepository) CreateReview(ctx context.Context, review *models.Review) error {
	args := m.Called(ctx, review)
	return args.Error(0)
}

func (m *MockReviewRepository) GetReviewByStudentAndCourse(ctx context.Context, studentID, courseID uint) (*models.Review, error) {
	args := m.Called(ctx, studentID, courseID)
	var r0 *models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) UpdateReview(ctx context.Context, review *models.Review) error {
	args := m.Called(ctx, review)
	return args.Error(0)
}

func (m *MockReviewRepository) GetReviewByID(ctx context.Context, reviewID uint) (*models.Review, error) {
	args := m.Called(ctx, reviewID)
	var r0 *models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) ListReviewsByCourseID(ctx context.Context, courseID uint, isAdminOrTeacher bool) ([]models.Review, error) {
	args := m.Called(ctx, courseID, isAdminOrTeacher)
	var r0 []models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).([]models.Review)
	}
	return r0, args.Error(1)
}

func (m *MockReviewRepository) GetCourseRatingStats(ctx context.Context, courseID uint) (map[int]int64, int64, float64, error) {
	args := m.Called(ctx, courseID)
	var r0 map[int]int64
	if args.Get(0) != nil {
		r0 = args.Get(0).(map[int]int64)
	}
	return r0, args.Get(1).(int64), args.Get(2).(float64), args.Error(3)
}

func (m *MockReviewRepository) ListAllReviews(ctx context.Context, page, limit int, search string) ([]models.Review, int64, error) {
	args := m.Called(ctx, page, limit, search)
	var r0 []models.Review
	if args.Get(0) != nil {
		r0 = args.Get(0).([]models.Review)
	}
	return r0, args.Get(1).(int64), args.Error(2)
}

// Note: MockCourseRepository and MockEnrollmentRepository are defined in quiz_usecase_test.go (same package)
// They are reused here without redeclaration.

// reviewCourseRepoMock is a testify-based wrapper used only in review tests
type reviewCourseRepoMock struct {
	mock.Mock
}

func (m *reviewCourseRepoMock) Create(ctx context.Context, course *models.Course) error {
	return nil
}
func (m *reviewCourseRepoMock) GetByID(ctx context.Context, id uint) (*models.Course, error) {
	args := m.Called(ctx, id)
	var r0 *models.Course
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Course)
	}
	return r0, args.Error(1)
}
func (m *reviewCourseRepoMock) Update(ctx context.Context, course *models.Course) error {
	return nil
}
func (m *reviewCourseRepoMock) Delete(ctx context.Context, id uint) error {
	return nil
}
func (m *reviewCourseRepoMock) GetBySlug(ctx context.Context, slug string) (*models.Course, error) {
	return nil, nil
}
func (m *reviewCourseRepoMock) GetDetails(ctx context.Context, idOrSlug string) (*models.Course, error) {
	return nil, nil
}
func (m *reviewCourseRepoMock) Search(ctx context.Context, c, k, p string, pg, l int) ([]models.Course, int64, error) {
	return nil, 0, nil
}
func (m *reviewCourseRepoMock) GetByTeacherID(ctx context.Context, teacherID uint) ([]models.Course, error) {
	return nil, nil
}
func (m *reviewCourseRepoMock) GetAdminCourses(ctx context.Context, status string) ([]models.Course, error) {
	return nil, nil
}

type reviewEnrollmentRepoMock struct {
	mock.Mock
}

func (m *reviewEnrollmentRepoMock) Create(ctx context.Context, e *models.Enrollment) error {
	return nil
}
func (m *reviewEnrollmentRepoMock) GetByID(ctx context.Context, id uint) (*models.Enrollment, error) {
	return nil, nil
}
func (m *reviewEnrollmentRepoMock) GetByStudentAndCourse(ctx context.Context, studentID, courseID uint) (*models.Enrollment, error) {
	args := m.Called(ctx, studentID, courseID)
	var r0 *models.Enrollment
	if args.Get(0) != nil {
		r0 = args.Get(0).(*models.Enrollment)
	}
	return r0, args.Error(1)
}
func (m *reviewEnrollmentRepoMock) ListByStudent(ctx context.Context, s uint) ([]models.Enrollment, error) {
	return nil, nil
}
func (m *reviewEnrollmentRepoMock) Update(ctx context.Context, e *models.Enrollment) error {
	return nil
}
func (m *reviewEnrollmentRepoMock) GetLessonProgress(ctx context.Context, e, l uint) (*models.LessonProgress, error) {
	return nil, nil
}
func (m *reviewEnrollmentRepoMock) CreateLessonProgress(ctx context.Context, p *models.LessonProgress) error {
	return nil
}
func (m *reviewEnrollmentRepoMock) UpdateLessonProgress(ctx context.Context, p *models.LessonProgress) error {
	return nil
}
func (m *reviewEnrollmentRepoMock) CountLessonsInCourse(ctx context.Context, c uint) (int64, error) {
	return 0, nil
}
func (m *reviewEnrollmentRepoMock) CountCompletedLessons(ctx context.Context, e uint) (int64, error) {
	return 0, nil
}
func (m *reviewEnrollmentRepoMock) GetEnrollmentsByCourse(ctx context.Context, c uint) ([]models.Enrollment, error) {
	return nil, nil
}


func TestSubmitReview(t *testing.T) {
	mockReviewRepo := new(MockReviewRepository)
	mockCourseRepo := new(reviewCourseRepoMock)
	mockEnrollmentRepo := new(reviewEnrollmentRepoMock)
	useCase := NewReviewUseCase(mockReviewRepo, mockCourseRepo, mockEnrollmentRepo)

	ctx := context.Background()

	t.Run("Success", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(1), uint(1)).Return(&models.Enrollment{}, nil).Once()
		mockReviewRepo.On("GetReviewByStudentAndCourse", ctx, uint(1), uint(1)).Return(nil, errors.New("not found")).Once()
		mockReviewRepo.On("CreateReview", ctx, mock.AnythingOfType("*models.Review")).Return(nil).Once()

		err := useCase.SubmitReview(ctx, 1, 1, 5, "Great course")
		assert.NoError(t, err)

		mockEnrollmentRepo.AssertExpectations(t)
		mockReviewRepo.AssertExpectations(t)
	})

	t.Run("Not Enrolled", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(2), uint(1)).Return(nil, errors.New("not found")).Once()

		err := useCase.SubmitReview(ctx, 2, 1, 5, "Great course")
		assert.Error(t, err)
		assert.IsType(t, &apperrors.AppError{}, err)

		mockEnrollmentRepo.AssertExpectations(t)
	})

	t.Run("Invalid Rating", func(t *testing.T) {
		mockEnrollmentRepo.On("GetByStudentAndCourse", ctx, uint(1), uint(1)).Return(&models.Enrollment{}, nil).Once()
		mockReviewRepo.On("GetReviewByStudentAndCourse", ctx, uint(1), uint(1)).Return(nil, errors.New("not found")).Once()

		err := useCase.SubmitReview(ctx, 1, 1, 6, "Great course")
		assert.Error(t, err)

		mockEnrollmentRepo.AssertExpectations(t)
		mockReviewRepo.AssertExpectations(t)
	})
}

func TestReplyToReview(t *testing.T) {
	mockReviewRepo := new(MockReviewRepository)
	mockCourseRepo := new(reviewCourseRepoMock)
	mockEnrollmentRepo := new(reviewEnrollmentRepoMock)
	useCase := NewReviewUseCase(mockReviewRepo, mockCourseRepo, mockEnrollmentRepo)

	ctx := context.Background()

	t.Run("Success", func(t *testing.T) {
		review := &models.Review{
			ID: 1,
			CourseID:  1,
			StudentID: 1,
			Rating:    5,
		}
		course := &models.Course{
			ID: 1,
			TeacherID: 1,
		}

		mockReviewRepo.On("GetReviewByID", ctx, uint(1)).Return(review, nil).Once()
		mockCourseRepo.On("GetByID", ctx, uint(1)).Return(course, nil).Once()
		mockReviewRepo.On("UpdateReview", ctx, mock.AnythingOfType("*models.Review")).Return(nil).Once()

		err := useCase.ReplyToReview(ctx, 1, 1, "Thank you")
		assert.NoError(t, err)

		mockReviewRepo.AssertExpectations(t)
		mockCourseRepo.AssertExpectations(t)
	})

	t.Run("Forbidden - Not the teacher", func(t *testing.T) {
		review := &models.Review{
			ID: 1,
			CourseID:  1,
		}
		course := &models.Course{
			ID: 1,
			TeacherID: 2, // Different teacher
		}

		mockReviewRepo.On("GetReviewByID", ctx, uint(1)).Return(review, nil).Once()
		mockCourseRepo.On("GetByID", ctx, uint(1)).Return(course, nil).Once()

		err := useCase.ReplyToReview(ctx, 1, 1, "Thank you")
		assert.Error(t, err)
		assert.IsType(t, &apperrors.AppError{}, err)

		mockReviewRepo.AssertExpectations(t)
		mockCourseRepo.AssertExpectations(t)
	})
}
